-- 기존 테이블 및 타입 삭제 (CASCADE로 의존성도 함께 삭제)
DROP POLICY IF EXISTS "Allow public access to all operations for labels" ON public.labels;
DROP POLICY IF EXISTS "Allow public access to all operations for documents" ON public.documents;
DROP TABLE IF EXISTS public.labels CASCADE;
DROP TABLE IF EXISTS public.documents CASCADE;
DROP TYPE IF EXISTS public.document_status CASCADE;

-- 문서 상태를 위한 ENUM 타입 생성
CREATE TYPE public.document_status AS ENUM (
    'PENDING',
    'INGESTING',
    'INGESTED',
    'FAILED'
);

-- 문서 정보를 저장할 테이블
CREATE TABLE public.documents (
    id uuid NOT NULL DEFAULT gen_random_uuid(),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    title text NOT NULL,
    content text NOT NULL,
    link text,
    status public.document_status NOT NULL DEFAULT 'PENDING'::public.document_status,
    theme text,
    summary text,
    CONSTRAINT documents_pkey PRIMARY KEY (id)
);

-- 테이블 및 컬럼에 대한 주석 추가
COMMENT ON TABLE public.documents IS '회의록 등 텍스트 문서 정보를 저장합니다.';
COMMENT ON COLUMN public.documents.id IS '고유 문서 ID';
COMMENT ON COLUMN public.documents.created_at IS '생성 일시';
COMMENT ON COLUMN public.documents.title IS '문서 제목';
COMMENT ON COLUMN public.documents.content IS '문서 원본 내용';
COMMENT ON COLUMN public.documents.link IS '문서 출처 URL (선택)';
COMMENT ON COLUMN public.documents.status IS '수집 처리 상태 (PENDING, INGESTING, INGESTED, FAILED)';
COMMENT ON COLUMN public.documents.theme IS '문서의 테마/카테고리 (개발, 설계, 기획, 마케팅, QA, 사업, 일반 회의, 기타)';
COMMENT ON COLUMN public.documents.summary IS '문서의 AI 생성 요약 (ingestion 시 생성됨)';

-- 문서의 메타데이터 레이블을 저장할 테이블
CREATE TABLE public.labels (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    document_id uuid NOT NULL,
    key text NOT NULL,
    value text NOT NULL,
    CONSTRAINT labels_pkey PRIMARY KEY (id),
    CONSTRAINT labels_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.documents (id) ON UPDATE CASCADE ON DELETE CASCADE
);

-- 테이블 및 컬럼에 대한 주석 추가
COMMENT ON TABLE public.labels IS '문서에 대한 메타데이터 레이블 (예: 날짜, 참여자)을 저장합니다.';
COMMENT ON COLUMN public.labels.document_id IS '참조하는 문서의 ID';
COMMENT ON COLUMN public.labels.key IS '레이블의 키 (예: "date")';
COMMENT ON COLUMN public.labels.value IS '레이블의 값 (예: "2024-05-21")';

-- RLS(Row Level Security) 활성화
ALTER TABLE public.documents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.labels ENABLE ROW LEVEL SECURITY;

-- 정책 생성: 모든 사용자가 모든 작업을 수행할 수 있도록 허용 (개발용)
CREATE POLICY "Allow public access to all operations for documents" ON public.documents
FOR ALL USING (true) WITH CHECK (true);

CREATE POLICY "Allow public access to all operations for labels" ON public.labels
FOR ALL USING (true) WITH CHECK (true);
